//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.Task1 = new HashSet<Task>();
        }
    
        public int id { get; set; }
        public string path { get; set; }
        public int resource_type_id { get; set; }
        public Nullable<int> task_id { get; set; }
    
        public virtual ResourceType ResourceType { get; set; }
        public virtual Task Task { get; set; }
        public virtual ICollection<Task> Task1 { get; set; }
    }
}
