//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolvedByUser
    {
        public int id { get; set; }
        public int task_id { get; set; }
        public int user_id { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
