//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskType
    {
        public TaskType()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<Task> Task { get; set; }
    }
}
