//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Location = new HashSet<Location>();
            this.Resource = new HashSet<Resource>();
            this.SolvedByUser = new HashSet<SolvedByUser>();
        }
    
        public int id { get; set; }
        public string task_name { get; set; }
        public int task_type_id { get; set; }
        public int bundle_id { get; set; }
        public Nullable<int> description_id { get; set; }
        public Nullable<int> minimum_to_find { get; set; }
    
        public virtual Bundle Bundle { get; set; }
        public virtual ICollection<Location> Location { get; set; }
        public virtual ICollection<Resource> Resource { get; set; }
        public virtual Resource Resource1 { get; set; }
        public virtual ICollection<SolvedByUser> SolvedByUser { get; set; }
        public virtual TaskType TaskType { get; set; }
    }
}
