//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SolvedByUser = new HashSet<SolvedByUser>();
            this.Visit = new HashSet<Visit>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime date_joined { get; set; }
    
        public virtual ICollection<SolvedByUser> SolvedByUser { get; set; }
        public virtual ICollection<Visit> Visit { get; set; }
    }
}
