//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int location_id { get; set; }
        public string photo_path { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
